EmployeeRatingApp/force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>companies details</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

EmployeeRatingApp/force-app/main/default/objects/Company__c/fields/Total_Ratings__c.field-meta.xml
<CustomField>
    <fullName>Total_Ratings__c</fullName>
    <label>Total Ratings</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

EmployeeRatingApp/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>employee&apos;s details</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

EmployeeRatingApp/force-app/main/default/objects/Employee__c/fields/Ratings__c.field-meta.xml
<CustomField>
    <fullName>Ratings__c</fullName>
    <description>ratings value</description>
    <label>Ratings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EmployeeRatingApp/force-app/main/default/classes/CompanyDetails.cls
public with sharing class CompanyDetails {

    @AuraEnabled(cacheable=true)
    public static List<String> getCompanyNames() {
        List<String> companyNames = new List<String>();
        for(Company__c company : [SELECT Name FROM Company__c]) {
            companyNames.add(company.Name);
        }
        return companyNames;
    }

    @AuraEnabled
    public static void createEmployee(String newName, String newRating, String newCompanyName) {
        try {
            Employee__c emp = new Employee__c();
            emp.Name = newName;
            emp.Ratings__c = newRating;
            emp.Company__r.Name = newCompanyName;
            insert emp;
             // Calculate average ratings for the company
            calculateAverageRatings(newCompanyName);

        } catch (Exception e) {
            throw new AuraHandledException('Error creating employee: ' + e.getMessage());
        }
    }

     // Method to calculate average ratings for a company
     public static void calculateAverageRatings(String companyName) {
        List<Employee__c> rating = [SELECT Ratings__c FROM Employee__c WHERE Company__c = :companyName];

        Integer total = 0;
        for(Employee__c ratings : rating){
            total += Integer.valueOf(ratings.Ratings__c);
        }

        Decimal avg = total/rating.size();

        Company__c cmp = [SELECT Id FROM Company__c WHERE Name = :companyName];
        cmp.Total_Ratings__c = avg;
        update cmp;
    }

}